# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d9454085bcd63127ce4769b770986e7bbcbe85c9210ce8a6f3345ecef341b6e8aa3894098ebdc20368da3992a2527bf93a0d37daf8018171fb9df1dbeac3298

test:
  secret_key_base: dfa027c3bb65c154ecbee3a070fdd1e3c851107ab036828566213ccf6b27f55d8695c6bd73a3d6b448bf8cd182841ef924cbfbd7fdafc5f98921a7d2acb3733c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
